{{ if not .Values.smtp-relay.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smtp-relay.fullname" . }}
  labels:
    {{- include "smtp-relay.labels" . | nindent 4 }}
data:
  {{ .Values.smtp-relay.smtp.passwordKey }}: {{ .Values.smtp-relay.smtp.password | b64enc }}
{{ end }}
